# Site configuration

# General Settings
title: Your awesome title
author: GitHub User
description: >  # this means to ignore newlines until "keywords:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

keywords: here is your site keywords
favicon: favicon.png

# url is the full website URL
# baseurl is the website's URL without the hostname
url:
baseurl: ""

# Image MUST be in 'assets/images/*'
author-image: profile.png
email: your-email@domain.com
phone: 123-456-789
# End

# social links
#twitter_username:
#github_username:
# facebook_username:
# linkedin_username:
# instagram_username:
# youtube_username:
# googleplus_username:





# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
exclude:
  - Gemfile
  - Gemfile.lock