# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url:
baseurl: ""
# Site General Setting
title: Your awesome title
author: GitHub User
favicon: favicon.png

# Image MUST be in 'assets/images/*'
author-image: profile.png
email: your-email@domain.com
phone: 123-456-789
# End


# Site menu settings
menu:
  - title: "SUMMARY"
    url: "#summary"
  - title: "Experience and History"
    url: "#experience"
  - title: "Education"
    url: "#education"
  - title: "Knowledge and Skills"
    url: "#knowledge"
  - title: "External Profiles"
    url:  "#profiles"
# End
